weather_in_city:
  path: /weather/{city}
  controller: App\Controller\WeatherController:cityAction
  requirements:
    city: \d+

app_logout:
  path: /logout
  methods: GET
# weather_by_country_and_city:
#   path: /weather/{country}/{city}
#   controller: App\Controller\WeatherController::weatherByCountryAndCity

weather_api:
  path: /weather/api/{type}/{country}/{city}
  controller: App\Controller\WeatherApiController:weatherTwigAction